### ISSUE TITLE
Breaks Nucleus' Chat Color

### ISSUE THREAD

**Issue by Mohron** [pie-flavor/ItemChat#1]
- ItemChat-1.2.1
- Nucleus-1.1.0-S5.1-MC1.10.2-plugin
- spongeforge-1.10.2-2281-5.2.0-BETA-2546

![image](https://user-images.githubusercontent.com/3623122/29256070-0c1b69fc-806d-11e7-9f8c-bf2c6ffa23fd.png)

**Comment by pie-flavor** [comment]
This plugin is written for API 6. Any functionality whatsoever on lower or higher major API releases is completely coincidental.
